# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 311cb2c5b81fff04afcc6f98480edd0670497ec866c6cde67b9afe4a62b26eaa7e5f0169d3149201f4b652769be6e5bcd49e6e776d01e77cd9920ce8698f0ab2

test:
  secret_key_base: bd35205a8506d6e08f68422777c1decb73ea9e439cd2a83b213287255fc66773cfc5df76d3c9754765ce602369f7ec0bd9bde4736f706389e850fbdb8fa97d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
